### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by avently** [juggernaut0/bigint#1]
Hello, @juggernaut0. Thank you for your work! Do you plan to make this library usable for everyone? Or it's just your personal solution?

I'm trying to find a cross-platform alternative to BigDecimal (which is obviously should be based on BigInteger) so your project looks promising. For now it's pretty buggy but bugs are not the only problem. Performance could be better.
I created my BigInteger and BigDecimal implementations but they have worse performance than your BigInteger :)

Some of the bugs I found while testing:
Wrong sum in some corner cases:
```
After this line:
https://github.com/juggernaut0/bigint/blob/master/src/commonMain/kotlin/com/github/juggernaut0/bigint/BigInteger.kt#L91

add:
if (carry > 0u) result[len] = carry.toUByte()
```
Wrong comparsion with negative values:
```
After this line:
https://github.com/juggernaut0/bigint/blob/master/src/commonMain/kotlin/com/github/juggernaut0/bigint/BigInteger.kt#L191

add:
val higher = if (neg) -1 else 1
val lower = if (neg) 1 else -1

change:
https://github.com/juggernaut0/bigint/blob/master/src/commonMain/kotlin/com/github/juggernaut0/bigint/BigInteger.kt#L197
https://github.com/juggernaut0/bigint/blob/master/src/commonMain/kotlin/com/github/juggernaut0/bigint/BigInteger.kt#L198

with:
if (a > b) return higher
if (a < b) return lower

```

Also divmod() method doesn't work in some situations. Can't show to you the correct code because I made another method for myself which do the same with different code. But to find an issues try to divide numbers like:
-something  /   something
something / -something
-something / - something

and you'll find wrong results. I just used BigInteger from Jvm for comparsion.

I searched some days ago over the github and in other popular sources for BigDecimal/BigInteger projects based on Kotlin-only and found a few but its can not be used in production. I really hope that you'll continue to work on this library and we will promote you somehow. I'm not alone who trying to find working multiplatform code for big numbers.
So, what's you plans?

**Comment by juggernaut0** [comment]
Hi @avently, thanks for your interest. I originally wrote this as a utility library for another personal project I was working on, but other difficulties led to that project being dropped and this library being somewhat abandoned.

You're welcome to make a pull request to fix the issues you mentioned, but as of right now I don't have any plans to actively work on this project.
